version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_PATH: $VITE_API_BASE_PATH
    depends_on:
      - postgres
      - fastapi

  fastapi:
    container_name: backend
    build: ./piccolo-fastapi
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./piccolo-fastapi:/usr/src/app
    ports:
      - 8000:8000
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: $POSTGRES_HOST
      DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    depends_on:
      - postgres

  postgres:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5433:5432"
    volumes:
      - fastapi-piccolo-db:/var/lib/postgresql/data

volumes:
  fastapi-piccolo-db:

networks:
  default:
    name: fastapi-piccolo
